name: Bundle Build Wolfi Packages

on:
  schedule:
    # Deploy at 7:23 AM (PST) every day.
    - cron: "23 15 * * *"
  workflow_dispatch:
    inputs:
      package_names:
        required: false
        type: string
        default: ""
        description: "comma separated list of package names to build. If empty, build all packages."

# Only run one build at a time to prevent out of sync signatures.
concurrency: 'bundle-runner-a'

permissions:
  contents: read

jobs:
  build:
    name: Build packages

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wolfi-dev/sdk:latest@sha256:32dbbda09149bdac1103c0740e7da8d8add0ac8ddcd9dd7bb12033068a1169e3

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: 'Trust the github workspace'
        run: |
          # This is to avoid fatal errors about "dubious ownership" because we are
          # running inside of a container action with the workspace mounted in.
          git config --global --add safe.directory "$(pwd)"

      - name: "Generate local signing key"
        run: |
          make local-melange.rsa

      - name: "bundle build"
        shell: bash
        env:
          BUNDLE_REPO: us-central1-docker.pkg.dev/staging-images-183e/bundles
          BUCKET: "wolfi-registry-destination/${{ github.run_id }}"
        run: |
          set -x
          set -v

          git --no-pager log --pretty=format="%ct" --name-only --no-merges

          COMMON_FLAGS=$(cat <<-END
            --keyring-append ./local-melange.rsa.pub \
            --keyring-append https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
            --repository-append https://packages.wolfi.dev/os
          END
          )

          BUNDLE=$(wolfictl bundle \
            --bundle-base ghcr.io/wolfi-dev/sdk:latest@sha256:32dbbda09149bdac1103c0740e7da8d8add0ac8ddcd9dd7bb12033068a1169e3 \
            --bundle-repo "${BUNDLE_REPO}" \
            ${COMMON_FLAGS} \
            --runner bubblewrap \
            --pipeline-dir ./pipelines \
            ${{ github.event.inputs.package_names }}
            )
          wolfictl build \
            --jobs 128 \
            --bucket "${BUCKET}" \
            --destination-bucket "${BUCKET}" \
            ${COMMON_FLAGS} \
            --k8s-namespace 'post-wolfi' \
            --service-account 'post-wolfi' \
            --trace /tmp/trace.json \
            --bundle "${BUNDLE}"

      - if: ${{ always() }}
        name: 'Upload trace to GitHub Artifacts'
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: trace-build.json
          path: /tmp/trace.json
          if-no-files-found: warn

  postrun:
    name: Notify Slack
    runs-on: ubuntu-latest
    if: failure() && false # TODO(kleung): remove `&& false` when ready to slack
    needs: [build]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - uses: rtCamp/action-slack-notify@4e5fb42d249be6a45a298f3c9543b111b02f7907 # v2.3.0
        env:
          SLACK_ICON: http://github.com/chainguard-dev.png?size=48
          SLACK_USERNAME: guardian
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: chainguard-images-alerts
          SLACK_MSG_AUTHOR: wolfi-bot
          SLACK_COLOR: "#8E1600"
          MSG_MINIMAL: "true"
          SLACK_TITLE: "[bundle build wolfi] failure: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          SLACK_MESSAGE: |
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
